emp_data = {
    "1": {
        "fname": "Swati",
        "lname": "Mehta",
        "fullname": "Swati Mehta",
        "age": "24",
        "city": "kolkata",
        "company": "tcs",
        "salary": "24000",
        "designation": "ase",
        "year": "2022",
    },
    "2": {
        "fname": "Rishav",
        "lname": "Anurag",
        "fullname": "Rishav Anurag",
        "age": "25",
        "city": "kolkata",
        "company": "tcs",
        "salary": "24000",
        "designation": "se",
        "year": "2021",
    },
    "3": {
        "fname": "Rishav1",
        "lname": "Anurag1",
        "fullname": "Rishav1 Anurag1",
        "age": "51",
        "city": "kolkata1",
        "company": "tcs1",
        "salary": "24001",
        "designation": "se1",
        "year": "2023",
    },
}
